/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemalocacao.view;

import java.util.*;
import static java.util.Calendar.*;
import javax.swing.JOptionPane;
import sistemalocacao.bean.*;
import sistemalocacao.dao.*;

/**
 *
 * @author marcelo
 */
public class VeiculoLocarForm extends javax.swing.JFrame {

    private ModeloTabelaClienteLocar modeloTabelaCliente;
    private ModeloTabelaVeiculoLocar modeloTabelaVeiculo;
    private int linhaClicada=-1;
    private List<Veiculo> lista= new ArrayList();
    private List<Van> listaVan = new ArrayList();
    private List<Automovel> listaAutomovel = new ArrayList();
    private List<Motocicleta> listaMotocicleta = new ArrayList();
    private List<Cliente> listaCliente = new ArrayList();
    /**
     * Creates new form VeiculoLocarForm
     */
    public VeiculoLocarForm() {
        modeloTabelaVeiculo = new ModeloTabelaVeiculoLocar();
        modeloTabelaCliente = new ModeloTabelaClienteLocar();
        initComponents();
        buscarVeiculosPor.addItem("Automovel");
        buscarVeiculosPor.addItem("Motocicleta");
        buscarVeiculosPor.addItem("Van");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dadoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaVeiculo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nomeTabelaVeiculo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipoBuscaClientes = new javax.swing.JComboBox<>();
        tipoBuscaVeiculos = new javax.swing.JComboBox<>();
        buscarVeiculosPor = new javax.swing.JComboBox<>();
        buscarClientes = new javax.swing.JButton();
        buscarVeiculos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        locarVeiculo = new javax.swing.JButton();
        qtdDias = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dadoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadoClienteActionPerformed(evt);
            }
        });

        tabelaCliente.setModel(modeloTabelaCliente);
        jScrollPane1.setViewportView(tabelaCliente);

        tabelaVeiculo.setModel(modeloTabelaVeiculo);
        jScrollPane2.setViewportView(tabelaVeiculo);

        jLabel1.setText("Selecionar Cliente");

        nomeTabelaVeiculo.setText("Selecionar Veiculo");

        jLabel3.setText("Buscar cliente por:");

        jLabel4.setText("Buscar veículo por:");

        tipoBuscaClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Sobrenome", "CPF" }));

        tipoBuscaVeiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Marca", "Categoria" }));
        tipoBuscaVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoBuscaVeiculosActionPerformed(evt);
            }
        });

        buscarClientes.setText("Buscar Cliente");
        buscarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClientesActionPerformed(evt);
            }
        });

        buscarVeiculos.setText("Buscar Veículos");
        buscarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarVeiculosActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantidade de dias da locação");

        locarVeiculo.setText("Locar Veículo");
        locarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locarVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(388, 388, 388)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(391, 391, 391)
                                .addComponent(nomeTabelaVeiculo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dadoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoBuscaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buscarClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buscarVeiculosPor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoBuscaVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buscarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(locarVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(27, 27, 27))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtdDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(nomeTabelaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipoBuscaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tipoBuscaVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarVeiculosPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtdDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarClientes)
                    .addComponent(buscarVeiculos)
                    .addComponent(locarVeiculo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dadoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dadoClienteActionPerformed

    private void buscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClientesActionPerformed
        String tipoBusca = tipoBuscaClientes.getSelectedItem().toString();
        Cliente cliente;
        List<Cliente> lista = new ArrayList();
        String nome;
        String sobrenome;
        Long cpf;
        ClienteDAO dao = new ClienteDAO();
        try {
            switch(tipoBusca){
                case "Nome":
                    nome = dadoCliente.getText();
                    lista = dao.buscaPorNome(nome);
                    break;
                case "Sobrenome":
                    sobrenome = dadoCliente.getText();
                    lista = dao.buscaPorSobrenome(sobrenome);
                    break;
                case "CPF":
                    cpf = Long.parseLong(dadoCliente.getText());
                    cliente = dao.pega(cpf);
                    lista.add(cliente);
                    break;
            }
            modeloTabelaCliente.setListaClientes(lista);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro ao escolher tipo de busca de clientes.Excecao = "+e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buscarClientesActionPerformed

    private void locarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locarVeiculoActionPerformed
        Veiculo veiculo = modeloTabelaVeiculo.getVeiculo(tabelaVeiculo.getSelectedRow());
        Cliente cliente = modeloTabelaCliente.getCliente(tabelaCliente.getSelectedRow());
        
        LocacaoDAO dao = new LocacaoDAO();
        Calendar hoje = new Calendar(YEAR+MONTH+DAY_OF_MONTH);
        try {
            veiculo.locar(qtdDias.getComponentCount(), hoje, cliente);
            dao.insere(veiculo.getLocacao());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro ao locar o veiculo.Excecao = "+e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_locarVeiculoActionPerformed

    private void buscarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarVeiculosActionPerformed
        VeiculoDAO dao = new VeiculoDAO();
        String tipoBusca = tipoBuscaVeiculos.getSelectedItem().toString();
        String buscarPor = buscarVeiculosPor.getSelectedItem().toString();
        try {
            listaAutomovel = dao.getListaAutomovel();
            listaMotocicleta = dao.getListaMotocicleta();
            listaVan = dao.getListaVan();
            switch(tipoBusca){
                case "Tipo":
                    switch(buscarPor){
                        case "Automovel":
                            lista = dao.getListaAutomovel();
                            break;
                        case "Motocicleta":
                            lista = dao.getListaMotocicleta();
                            break;
                        case "Van":
                            lista = dao.getListaVan();
                            break;
                        default:
                            JOptionPane.showMessageDialog(null,"Erro ao buscar veiculo por tipo.", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                case "Marca":
                    lista.addAll(listaAutomovel);
                    lista.addAll(listaMotocicleta);
                    lista.addAll(listaVan);
                    for(Veiculo veiculo: lista)
                        if(veiculo.getMarca().toString() != buscarPor)
                            lista.remove(veiculo);
                    break;
                case "Categoria":
                    lista.addAll(listaAutomovel);
                    lista.addAll(listaMotocicleta);
                    lista.addAll(listaVan);
                    for(Veiculo veiculo: lista)
                        if(veiculo.getCategoria().toString() != buscarPor)
                            lista.remove(veiculo);
                    break;
                default:
                    JOptionPane.showMessageDialog(null,"Ocorreu um erro na busca de veiculo.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            modeloTabelaVeiculo.setListaVeiculos(lista);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Ocorreu um erro na busca de veiculo. Excecao = "+e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buscarVeiculosActionPerformed

    private void tipoBuscaVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoBuscaVeiculosActionPerformed
        String tipoBusca = tipoBuscaVeiculos.getSelectedItem().toString();
        List<Veiculo> lista = new ArrayList();
        switch(tipoBusca){
            case "Tipo":
                buscarVeiculosPor.removeAllItems();
                buscarVeiculosPor.addItem("Automovel");
                buscarVeiculosPor.addItem("Motocicleta");
                buscarVeiculosPor.addItem("Van");
                break;
            case "Marca":
                buscarVeiculosPor.removeAllItems();
                Marca[] marcas = Marca.values();
                for(Marca marca: marcas)
                    buscarVeiculosPor.addItem(marca.toString());
                break;
            case "Categoria":
                buscarVeiculosPor.removeAllItems();
                Categoria[] categorias = Categoria.values();
                for(Categoria categoria: categorias)
                    buscarVeiculosPor.addItem(categoria.toString());
                break;
            default:
                JOptionPane.showMessageDialog(null,"Ocorreu um erro na selecao do tipo de busca de veiculo.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tipoBuscaVeiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeiculoLocarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeiculoLocarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeiculoLocarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiculoLocarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeiculoLocarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarClientes;
    private javax.swing.JButton buscarVeiculos;
    private javax.swing.JComboBox<String> buscarVeiculosPor;
    private javax.swing.JTextField dadoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton locarVeiculo;
    private javax.swing.JLabel nomeTabelaVeiculo;
    private javax.swing.JSpinner qtdDias;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTable tabelaVeiculo;
    private javax.swing.JComboBox<String> tipoBuscaClientes;
    private javax.swing.JComboBox<String> tipoBuscaVeiculos;
    // End of variables declaration//GEN-END:variables
}
